/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#ffffff",
        foreground: "#1c1e26",
        card: "#ffffff",
        "card-fg": "#1c1e26",
        popover: "#ffffff",
        "popover-fg": "#1c1e26",
        primary: "#0061ff",
        "primary-fg": "#f4f6fb",
        secondary: "#f4f4f5",
        "secondary-fg": "#34323c",
        muted: "#f3f4f6",
        "muted-fg": "#848a9e",
        accent: "#f3f4f6",
        "accent-fg": "#2d313d",
        destructive: "#df2a1a",
        border: "#e9eaec",
        input: "#e9eaec",
        ring: "#adb2c3",
        "chart-1": "#93c5fd",
        "chart-2": "#60a5fa",
        "chart-3": "#3b82f6",
        "chart-4": "#2563eb",
        "chart-5": "#1d4ed8",

        dark: {
          bg: "#1c1e26",
          fg: "#f8f9fa",
          card: "#2d313d",
          "card-fg": "#f8f9fa",
          popover: "#2d313d",
          "popover-fg": "#f8f9fa",
          primary: "#3e74ff",
          "primary-fg": "#f4f6fb",
          secondary: "#3f3e46",
          "secondary-fg": "#ffffff",
          muted: "#33394b",
          "muted-fg": "#adb2c3",
          accent: "#33394b",
          "accent-fg": "#f8f9fa",
          destructive: "#ff5252",
          border: "rgba(255, 255, 255, 0.1)",
          input: "rgba(255, 255, 255, 0.15)",
          ring: "#848a9e",
        },
      },
    },
  },
  plugins: [],
};
